// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBS3fd5LqpqzdWxLL1A-dIbuYQoCdA-20',
    appId: '1:546437856933:web:d883d3a8fb0d3f6060d74c',
    messagingSenderId: '546437856933',
    projectId: 'manups-lms-finapp-2026',
    authDomain: 'manups-lms-finapp-2026.firebaseapp.com',
    storageBucket: 'manups-lms-finapp-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAhtp_HvjB4IG1cGAwjsiW6BPo1mbElzA',
    appId: '1:546437856933:android:28fc6736485e4cd760d74c',
    messagingSenderId: '546437856933',
    projectId: 'manups-lms-finapp-2026',
    storageBucket: 'manups-lms-finapp-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkpOUTYFxLXalE-pOGT6iT7y1UxMWt3uI',
    appId: '1:546437856933:ios:43286b061eca30fe60d74c',
    messagingSenderId: '546437856933',
    projectId: 'manups-lms-finapp-2026',
    storageBucket: 'manups-lms-finapp-2026.firebasestorage.app',
    iosBundleId: 'io.flutter.demo.gallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkpOUTYFxLXalE-pOGT6iT7y1UxMWt3uI',
    appId: '1:546437856933:ios:43286b061eca30fe60d74c',
    messagingSenderId: '546437856933',
    projectId: 'manups-lms-finapp-2026',
    storageBucket: 'manups-lms-finapp-2026.firebasestorage.app',
    iosBundleId: 'io.flutter.demo.gallery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBS3fd5LqpqzdWxLL1A-dIbuYQoCdA-20',
    appId: '1:546437856933:web:ebcb4c8ef32db6b060d74c',
    messagingSenderId: '546437856933',
    projectId: 'manups-lms-finapp-2026',
    authDomain: 'manups-lms-finapp-2026.firebaseapp.com',
    storageBucket: 'manups-lms-finapp-2026.firebasestorage.app',
  );
}
